typography_spectrum: 0.19842778542079031
content_rating:
  adult: false
color:
  brandStrength: 0.7380557772703469
  lightness: 0.13878900394774973
  saturation: 0.3827695557847619
  rhythmicContrast: 0.32220642478205264
  brandColors:
    - '#FFFFFF'
    - '#012A40'
    - '#764944'
    - '#B67C54'
    - '#DBB67F'
opengraph:
  appId: 'https://www.facebook.com/ervey.mx'
layout_spectrum: 0.4726242597680539
name: Ervey.mx
navigation:
  - name: instagram
    url: 'https://www.instagram.com/ervey.mx/'
    type: external
